version: '3.1'
services:
    mysql:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: moviedb
      ports:
        - '3306:3306'
      networks:
        - myapp-network
    myapp:
      build:
        dockerfile: ./laravel-dockerfile
        context: .
      image: leovene/moviedb
      container_name: moviedb
      ports:
        - '8080:8080'
      depends_on:
        - mysql
      networks:
        - myapp-network
networks:
  myapp-network:
    driver: bridge
